# Generated by Django 5.2 on 2025-08-21 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input_image', models.ImageField(upload_to='comparison_inputs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=50)),
                ('processed_image', models.ImageField(upload_to='comparison_outputs/')),
                ('psnr', models.FloatField(blank=True, null=True)),
                ('image_quality', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField()),
                ('bitrate', models.FloatField(blank=True, null=True)),
                ('predicted_class', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_index', models.IntegerField(blank=True, null=True)),
                ('decode_time', models.FloatField(blank=True, null=True)),
                ('scale_factor', models.CharField(max_length=10)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='API.comparisonsession')),
            ],
            options={
                'unique_together': {('session', 'algorithm_name', 'scale_factor')},
            },
        ),
    ]
